name: sass-spec
description: Check out Dart Sass, build it, and link it into package.json.
runs:
  using: composite
  steps:
    - name: Check out Dart Sass
      id: clone
      uses: sass/clone-linked-repo@skip
      with:
        repo: sass/dart-sass
        default: null

    - uses: dart-lang/setup-dart@v1
      if: steps.clone.outputs.skip == 'false'

    - run: dart pub get
      working-directory: dart-sass
      shell: bash
      if: steps.clone.outputs.skip == 'false'

    - name: Build Dart Sass
      run: dart run grinder pkg-npm-dev
      working-directory: dart-sass
      shell: bash
      if: steps.clone.outputs.skip == 'false'

    - name: Install Dart Sass
      run: npm install dart-sass/build/npm
      if: steps.clone.outputs.skip == 'false'
      shell: bash
      
