export default [
  {
    name: 'color',
    functions: [
      'red',
      'green',
      'blue',
      'mix',
      'invert',
      'hue',
      'saturation',
      'lightness',
      'complement',
      'adjust-hue',
      'lighten',
      'darken',
      'saturate',
      'desaturate',
      'grayscale',
      'hwb',
      'whiteness',
      'blackness',
      'opacify',
      'fade-in',
      'transparentize',
      'fade-out',
      'alpha',
      'opacity',
      'adjust',
      'scale',
      'change',
      'ie-hex-str',
    ],
  },
  {
    name: 'list',
    functions: [
      'length',
      'nth',
      'set-nth',
      'join',
      'append',
      'zip',
      'index',
      'is-bracketed',
      'separator',
      'slash',
    ],
  },
  {
    name: 'map',
    functions: [
      'get',
      'set',
      'merge',
      'remove',
      'keys',
      'values',
      'has-key',
      'deep-merge',
      'deep-remove',
    ],
  },
  {
    name: 'math',
    functions: [
      'abs',
      'acos',
      'asin',
      'atan',
      'atan2',
      'ceil',
      'clamp',
      'cos',
      'compatible',
      'floor',
      'hypot',
      'is-unitless',
      'log',
      'max',
      'min',
      'percentage',
      'pow',
      'random',
      'round',
      'sin',
      'sqrt',
      'tan',
      'unit',
      'div',
    ],
    variables: [
      'e',
      'pi',
      'epsilon',
      'max-safe-integer',
      'min-safe-integer',
      'max-number',
      'min-number',
    ],
  },
  {
    name: 'meta',
    functions: [
      'feature-exists',
      'inspect',
      'type-of',
      'keywords',
      'calc-name',
      'calc-args',
      'accepts-content',
      'global-variable-exists',
      'variable-exists',
      'function-exists',
      'mixin-exists',
      'content-exists',
      'module-variables',
      'module-functions',
      'module-mixins',
      'get-function',
      'get-mixin',
      'call',
    ],
  },
  {
    name: 'selector',
    functions: [
      'is-superselector',
      'simple-selectors',
      'parse',
      'nest',
      'append',
      'extend',
      'replace',
      'unify',
    ],
  },
  {
    name: 'string',
    functions: [
      'unquote',
      'quote',
      'to-upper-case',
      'to-lower-case',
      'length',
      'insert',
      'index',
      'slice',
      'unique-id',
      'split',
    ],
  },
] as const;
